// ReSharper disable InconsistentNaming
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
namespace FrikanUtils.Spawnpoints.LootSpawn;

/// <summary>
/// Represents different places in a room we can spawn loot at.
/// </summary>
public enum LootPoint
{
    IntercomCrate,
    IntercomDesk,
    IntercomDeskSide,
    PCsDesk,
    PCsDeskAlt,
    PCsShelf,
    PCsShelfAlt,
    PCsCubicle,
    PCsSmallLedge,
    PCsSmallLedgeAlt,
    PCsSmallDesk,
    PCsSmallDeskAlt,
    ShelterWorkstation,
    ShelterWorkstationAlt,
    PCsStoriedDesk,
    PCsStoriedDeskAlt,
    PCsStoriedShelf,
    PCsStoriedShelfAlt,
    PCsStoriedWorkstation,
    PCsStoriedWorkstationAlt,
    Scp049Spawn173,
    Scp049Spawn173Outside,
    Scp049Spawn,
    Scp049Armory,
    Scp049ArmoyWorkstation,
    Scp079Intermediate,
    Scp079Table,
    Scp079Workstation,
    Scp096,
    Scp106Outside,
    Scp106Inside,
    Scp939Desk,
    Scp939Containment,
    HczCheckpointDesk,
    HczCheckpointHcz,
    HczCheckpointEz,
    MicroHIDDesk,
    MicroHIDDeskAlt,
    MicroHIDContainment,
    TestRoomDesk,
    Lcz173Desk,
    Lcz173Containment,
    Lcz173Entrance,
    Lcz173Upstairs,
    Scp330Desk,
    Scp330DeskAlt,
    Scp330Table,
    Gr18Containment,
    Gr18Shelve,
    Scp914Shelve,
    LczPCsDesk,
    LczPCsDeskAlt,
    WCs,
    WCsAlt
}