using LabApi.Features.Console;

namespace FrikanUtils.ServerSpecificSettings;

internal class FieldIdhandler
{
    private int _internalIdCounter = SSSHandler.LowestReservedId;

    private const ushort MenuOffset = 1; // Reserve IDs (prefix 0) 0 - 65535 for base game settings

    public int GetId(string menuId, ushort? fieldId)
    {
        if (!fieldId.HasValue)
        {
            // Remove one from the internal counter and return the new value.
            return --_internalIdCounter;
        }

        var menuIndex = UtilitiesPlugin.AutoGeneratedConfig.ServerSettingMenus.FindIndex(x => x == menuId);
        if (menuIndex == -1) // If we did not find an entry, add one
        {
            menuIndex = UtilitiesPlugin.AutoGeneratedConfig.ServerSettingMenus.Count;
            UtilitiesPlugin.AutoGeneratedConfig.ServerSettingMenus.Add(menuId);

            Logger.Debug($"Could not find the menu ID: {menuId}, adding to the config",
                UtilitiesPlugin.PluginConfig.Debug);

            // Save the config
            UtilitiesPlugin.Save();
        }

        return (menuIndex + MenuOffset) << 16 | fieldId.Value;
    }

    public void Reset()
    {
        _internalIdCounter = SSSHandler.LowestReservedId;
    }
}