using System.Collections.Generic;
using System.ComponentModel;
using MapGeneration.Holidays;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

namespace FrikanUtils.Config;

public class AutoGeneratedConfig
{
    [Description("Holiday override for debugging purposes. Makes the server think the event is currently running.")]
    public HolidayType OverrideHoliday { get; set; }
    
    [Description("[Automatically generated] List of Server Specific Settings menus to assist in getting IDs")]
    public List<string> ServerSettingMenus { get; set; } = [];

    [Description("[Automatically generated] List of Global Client settings, " +
                 "ensuring they are always given the same ID")]
    public List<string> GlobalClientSettings { get; set; } = [];
}